// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/pdu.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientMode int32

const (
	ClientMode_MEASURE ClientMode = 0
	ClientMode_STRESS  ClientMode = 1
)

var ClientMode_name = map[int32]string{
	0: "MEASURE",
	1: "STRESS",
}

var ClientMode_value = map[string]int32{
	"MEASURE": 0,
	"STRESS":  1,
}

func (x ClientMode) String() string {
	return proto.EnumName(ClientMode_name, int32(x))
}

func (ClientMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{0}
}

type HelloRequest struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mode                 ClientMode `protobuf:"varint,3,opt,name=mode,proto3,enum=protos.ClientMode" json:"mode,omitempty"`
	Nid                  string     `protobuf:"bytes,4,opt,name=nid,proto3" json:"nid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetMode() ClientMode {
	if m != nil {
		return m.Mode
	}
	return ClientMode_MEASURE
}

func (m *HelloRequest) GetNid() string {
	if m != nil {
		return m.Nid
	}
	return ""
}

type HelloResponse struct {
	Cid                  uint32   `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Ok                   bool     `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *HelloResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CollectRequest struct {
	Cid                  uint32         `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Data                 []*MeasureData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Time                 int64          `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CollectRequest) Reset()         { *m = CollectRequest{} }
func (m *CollectRequest) String() string { return proto.CompactTextString(m) }
func (*CollectRequest) ProtoMessage()    {}
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{2}
}

func (m *CollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRequest.Unmarshal(m, b)
}
func (m *CollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRequest.Marshal(b, m, deterministic)
}
func (m *CollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRequest.Merge(m, src)
}
func (m *CollectRequest) XXX_Size() int {
	return xxx_messageInfo_CollectRequest.Size(m)
}
func (m *CollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRequest proto.InternalMessageInfo

func (m *CollectRequest) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *CollectRequest) GetData() []*MeasureData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CollectRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type CollectResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectResponse) Reset()         { *m = CollectResponse{} }
func (m *CollectResponse) String() string { return proto.CompactTextString(m) }
func (*CollectResponse) ProtoMessage()    {}
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{3}
}

func (m *CollectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectResponse.Unmarshal(m, b)
}
func (m *CollectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectResponse.Marshal(b, m, deterministic)
}
func (m *CollectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectResponse.Merge(m, src)
}
func (m *CollectResponse) XXX_Size() int {
	return xxx_messageInfo_CollectResponse.Size(m)
}
func (m *CollectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectResponse proto.InternalMessageInfo

func (m *CollectResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type NodeCollectRequest struct {
	Nid                  string         `protobuf:"bytes,1,opt,name=nid,proto3" json:"nid,omitempty"`
	Data                 []*MeasureData `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	Time                 int64          `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeCollectRequest) Reset()         { *m = NodeCollectRequest{} }
func (m *NodeCollectRequest) String() string { return proto.CompactTextString(m) }
func (*NodeCollectRequest) ProtoMessage()    {}
func (*NodeCollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{4}
}

func (m *NodeCollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeCollectRequest.Unmarshal(m, b)
}
func (m *NodeCollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeCollectRequest.Marshal(b, m, deterministic)
}
func (m *NodeCollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeCollectRequest.Merge(m, src)
}
func (m *NodeCollectRequest) XXX_Size() int {
	return xxx_messageInfo_NodeCollectRequest.Size(m)
}
func (m *NodeCollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeCollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeCollectRequest proto.InternalMessageInfo

func (m *NodeCollectRequest) GetNid() string {
	if m != nil {
		return m.Nid
	}
	return ""
}

func (m *NodeCollectRequest) GetData() []*MeasureData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *NodeCollectRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type MeasureData struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                uint64   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeasureData) Reset()         { *m = MeasureData{} }
func (m *MeasureData) String() string { return proto.CompactTextString(m) }
func (*MeasureData) ProtoMessage()    {}
func (*MeasureData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{5}
}

func (m *MeasureData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeasureData.Unmarshal(m, b)
}
func (m *MeasureData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeasureData.Marshal(b, m, deterministic)
}
func (m *MeasureData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeasureData.Merge(m, src)
}
func (m *MeasureData) XXX_Size() int {
	return xxx_messageInfo_MeasureData.Size(m)
}
func (m *MeasureData) XXX_DiscardUnknown() {
	xxx_messageInfo_MeasureData.DiscardUnknown(m)
}

var xxx_messageInfo_MeasureData proto.InternalMessageInfo

func (m *MeasureData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MeasureData) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NodeControlRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeControlRequest) Reset()         { *m = NodeControlRequest{} }
func (m *NodeControlRequest) String() string { return proto.CompactTextString(m) }
func (*NodeControlRequest) ProtoMessage()    {}
func (*NodeControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{6}
}

func (m *NodeControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeControlRequest.Unmarshal(m, b)
}
func (m *NodeControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeControlRequest.Marshal(b, m, deterministic)
}
func (m *NodeControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeControlRequest.Merge(m, src)
}
func (m *NodeControlRequest) XXX_Size() int {
	return xxx_messageInfo_NodeControlRequest.Size(m)
}
func (m *NodeControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeControlRequest proto.InternalMessageInfo

func (m *NodeControlRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeControlRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NodeControlResponse struct {
	Asd                  string   `protobuf:"bytes,1,opt,name=asd,proto3" json:"asd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeControlResponse) Reset()         { *m = NodeControlResponse{} }
func (m *NodeControlResponse) String() string { return proto.CompactTextString(m) }
func (*NodeControlResponse) ProtoMessage()    {}
func (*NodeControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{7}
}

func (m *NodeControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeControlResponse.Unmarshal(m, b)
}
func (m *NodeControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeControlResponse.Marshal(b, m, deterministic)
}
func (m *NodeControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeControlResponse.Merge(m, src)
}
func (m *NodeControlResponse) XXX_Size() int {
	return xxx_messageInfo_NodeControlResponse.Size(m)
}
func (m *NodeControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeControlResponse proto.InternalMessageInfo

func (m *NodeControlResponse) GetAsd() string {
	if m != nil {
		return m.Asd
	}
	return ""
}

type ClientControlRequest struct {
	Cid                  uint32   `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientControlRequest) Reset()         { *m = ClientControlRequest{} }
func (m *ClientControlRequest) String() string { return proto.CompactTextString(m) }
func (*ClientControlRequest) ProtoMessage()    {}
func (*ClientControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{8}
}

func (m *ClientControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientControlRequest.Unmarshal(m, b)
}
func (m *ClientControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientControlRequest.Marshal(b, m, deterministic)
}
func (m *ClientControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientControlRequest.Merge(m, src)
}
func (m *ClientControlRequest) XXX_Size() int {
	return xxx_messageInfo_ClientControlRequest.Size(m)
}
func (m *ClientControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientControlRequest proto.InternalMessageInfo

func (m *ClientControlRequest) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

type ClientControlResponse struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args                 []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Repeat               bool     `protobuf:"varint,4,opt,name=repeat,proto3" json:"repeat,omitempty"`
	RepeatDelay          uint32   `protobuf:"varint,5,opt,name=repeatDelay,proto3" json:"repeatDelay,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientControlResponse) Reset()         { *m = ClientControlResponse{} }
func (m *ClientControlResponse) String() string { return proto.CompactTextString(m) }
func (*ClientControlResponse) ProtoMessage()    {}
func (*ClientControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcd50c56a5d9ee9c, []int{9}
}

func (m *ClientControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientControlResponse.Unmarshal(m, b)
}
func (m *ClientControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientControlResponse.Marshal(b, m, deterministic)
}
func (m *ClientControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientControlResponse.Merge(m, src)
}
func (m *ClientControlResponse) XXX_Size() int {
	return xxx_messageInfo_ClientControlResponse.Size(m)
}
func (m *ClientControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientControlResponse proto.InternalMessageInfo

func (m *ClientControlResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ClientControlResponse) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ClientControlResponse) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ClientControlResponse) GetRepeat() bool {
	if m != nil {
		return m.Repeat
	}
	return false
}

func (m *ClientControlResponse) GetRepeatDelay() uint32 {
	if m != nil {
		return m.RepeatDelay
	}
	return 0
}

func init() {
	proto.RegisterEnum("protos.ClientMode", ClientMode_name, ClientMode_value)
	proto.RegisterType((*HelloRequest)(nil), "protos.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "protos.HelloResponse")
	proto.RegisterType((*CollectRequest)(nil), "protos.CollectRequest")
	proto.RegisterType((*CollectResponse)(nil), "protos.CollectResponse")
	proto.RegisterType((*NodeCollectRequest)(nil), "protos.NodeCollectRequest")
	proto.RegisterType((*MeasureData)(nil), "protos.MeasureData")
	proto.RegisterType((*NodeControlRequest)(nil), "protos.NodeControlRequest")
	proto.RegisterType((*NodeControlResponse)(nil), "protos.NodeControlResponse")
	proto.RegisterType((*ClientControlRequest)(nil), "protos.ClientControlRequest")
	proto.RegisterType((*ClientControlResponse)(nil), "protos.ClientControlResponse")
}

func init() { proto.RegisterFile("protos/pdu.proto", fileDescriptor_dcd50c56a5d9ee9c) }

var fileDescriptor_dcd50c56a5d9ee9c = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xad, 0xed, 0x34, 0x6d, 0xc7, 0x24, 0x44, 0xd3, 0xb4, 0x58, 0x01, 0x24, 0x63, 0x09, 0x1a,
	0x71, 0x28, 0x10, 0x0e, 0x70, 0xe0, 0x02, 0x4d, 0x24, 0x2e, 0x01, 0xb4, 0xa6, 0xe2, 0x88, 0xb6,
	0xde, 0x15, 0x58, 0x5d, 0x7b, 0x83, 0xbd, 0xae, 0xc4, 0xa7, 0xf0, 0xad, 0x5c, 0x90, 0x77, 0x6d,
	0xc7, 0xb1, 0x01, 0x09, 0x71, 0x7b, 0x3b, 0x3b, 0xf3, 0xe6, 0xed, 0xbc, 0xb1, 0x61, 0xb2, 0xc9,
	0xa4, 0x92, 0xf9, 0x93, 0x0d, 0x2b, 0xce, 0x35, 0xc4, 0xa1, 0x89, 0x04, 0x02, 0x6e, 0xbd, 0xe5,
	0x42, 0x48, 0xc2, 0xbf, 0x15, 0x3c, 0x57, 0x38, 0x06, 0x3b, 0x66, 0x9e, 0xe5, 0x5b, 0xf3, 0x23,
	0x62, 0xc7, 0x0c, 0x11, 0x06, 0x29, 0x4d, 0xb8, 0x67, 0xeb, 0x88, 0xc6, 0xf8, 0x08, 0x06, 0x89,
	0x64, 0xdc, 0x73, 0x7c, 0x6b, 0x3e, 0x5e, 0xa0, 0x61, 0xcc, 0xcf, 0x2f, 0x44, 0xcc, 0x53, 0xb5,
	0x96, 0x8c, 0x13, 0x7d, 0x8f, 0x13, 0x70, 0xd2, 0x98, 0x79, 0x03, 0x5d, 0x5a, 0xc2, 0xe0, 0x19,
	0x8c, 0xaa, 0x6e, 0xf9, 0x46, 0xa6, 0xb9, 0x4e, 0x89, 0xaa, 0x7e, 0x23, 0x52, 0xc2, 0x52, 0x80,
	0xbc, 0xd6, 0xed, 0x0e, 0x89, 0x2d, 0xaf, 0x83, 0xcf, 0x30, 0xbe, 0x90, 0x42, 0xf0, 0x48, 0xd5,
	0x12, 0xfb, 0x35, 0x67, 0x30, 0x60, 0x54, 0x51, 0xcf, 0xf6, 0x9d, 0xb9, 0xbb, 0x38, 0xae, 0x05,
	0xad, 0x39, 0xcd, 0x8b, 0x8c, 0x2f, 0xa9, 0xa2, 0x44, 0x27, 0x94, 0xaf, 0x51, 0x71, 0x62, 0x94,
	0x3b, 0x44, 0xe3, 0xe0, 0x01, 0xdc, 0x6e, 0x1a, 0x54, 0xaa, 0x8c, 0x06, 0xab, 0xd1, 0x10, 0x01,
	0xbe, 0x93, 0x8c, 0xf7, 0x75, 0xa4, 0xcd, 0xac, 0x4a, 0xf8, 0x7f, 0x3a, 0x5e, 0x80, 0xdb, 0x4a,
	0x6c, 0x06, 0x6f, 0xb5, 0x06, 0x3f, 0x85, 0xfd, 0x1b, 0x2a, 0x0a, 0xe3, 0xc6, 0x80, 0x98, 0x43,
	0xf0, 0xb2, 0x56, 0x97, 0xaa, 0x4c, 0x8a, 0x7f, 0x30, 0x32, 0x38, 0x83, 0xe3, 0x9d, 0xca, 0xad,
	0x29, 0x34, 0x6f, 0x1e, 0x46, 0x73, 0x16, 0xcc, 0x61, 0x6a, 0xdc, 0xed, 0x34, 0xe9, 0x59, 0x11,
	0xfc, 0xb0, 0xe0, 0xa4, 0x93, 0x5a, 0xb1, 0x7a, 0x70, 0xc0, 0x53, 0x7a, 0x25, 0x38, 0xab, 0x26,
	0x5b, 0x1f, 0xcb, 0x9b, 0x48, 0x26, 0x09, 0x4d, 0x59, 0xa5, 0xae, 0x3e, 0x96, 0xa2, 0x69, 0xf6,
	0x25, 0xf7, 0x1c, 0xdf, 0x29, 0x45, 0x97, 0x18, 0x4f, 0x61, 0x98, 0xf1, 0x0d, 0xa7, 0x4a, 0x2f,
	0xd6, 0x21, 0xa9, 0x4e, 0xe8, 0x83, 0x6b, 0xd0, 0x92, 0x0b, 0xfa, 0xdd, 0xdb, 0xd7, 0x9a, 0xda,
	0xa1, 0xc7, 0x0f, 0x01, 0xb6, 0x3b, 0x8a, 0x2e, 0x1c, 0xac, 0x57, 0xaf, 0xc3, 0x4b, 0xb2, 0x9a,
	0xec, 0x21, 0xc0, 0x30, 0xfc, 0x48, 0x56, 0x61, 0x38, 0xb1, 0x16, 0x3f, 0x6d, 0x38, 0xfa, 0xc0,
	0x8a, 0x90, 0x67, 0x37, 0x3c, 0xc3, 0x57, 0xe0, 0x9a, 0x22, 0xbd, 0xb8, 0x38, 0xad, 0x4d, 0x6d,
	0x7f, 0x35, 0xb3, 0x93, 0x4e, 0xd4, 0x3c, 0x39, 0xd8, 0xc3, 0x37, 0x30, 0xaa, 0xa7, 0xa1, 0x77,
	0x07, 0x4f, 0x9b, 0xaf, 0x65, 0x67, 0x99, 0x66, 0x77, 0x7a, 0xf1, 0x86, 0x63, 0x09, 0x6e, 0x6b,
	0xfb, 0x70, 0x56, 0x67, 0xf6, 0x57, 0xf2, 0x6f, 0x2c, 0xef, 0x61, 0xf2, 0x89, 0xaa, 0xe8, 0x6b,
	0xcb, 0xf0, 0x2e, 0x55, 0xdb, 0xda, 0xd9, 0xdd, 0xdf, 0xde, 0xd5, 0x74, 0x4f, 0x2d, 0xbc, 0x04,
	0xd4, 0x84, 0x3b, 0x6e, 0xe3, 0xbd, 0xdd, 0xbf, 0x41, 0x87, 0xf4, 0xfe, 0x1f, 0x6e, 0xb7, 0xb4,
	0x57, 0xe6, 0xc7, 0xf4, 0xfc, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x9b, 0x84, 0xf0, 0xb3,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PduServerClient is the client API for PduServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PduServerClient interface {
	ClientHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	ClientCollect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error)
	NodeCollect(ctx context.Context, in *NodeCollectRequest, opts ...grpc.CallOption) (*CollectResponse, error)
	WatchNodeControl(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (PduServer_WatchNodeControlClient, error)
	WatchClientControl(ctx context.Context, in *ClientControlRequest, opts ...grpc.CallOption) (PduServer_WatchClientControlClient, error)
}

type pduServerClient struct {
	cc *grpc.ClientConn
}

func NewPduServerClient(cc *grpc.ClientConn) PduServerClient {
	return &pduServerClient{cc}
}

func (c *pduServerClient) ClientHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/protos.PduServer/ClientHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pduServerClient) ClientCollect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (*CollectResponse, error) {
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, "/protos.PduServer/ClientCollect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pduServerClient) NodeCollect(ctx context.Context, in *NodeCollectRequest, opts ...grpc.CallOption) (*CollectResponse, error) {
	out := new(CollectResponse)
	err := c.cc.Invoke(ctx, "/protos.PduServer/NodeCollect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pduServerClient) WatchNodeControl(ctx context.Context, in *NodeControlRequest, opts ...grpc.CallOption) (PduServer_WatchNodeControlClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PduServer_serviceDesc.Streams[0], "/protos.PduServer/WatchNodeControl", opts...)
	if err != nil {
		return nil, err
	}
	x := &pduServerWatchNodeControlClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PduServer_WatchNodeControlClient interface {
	Recv() (*NodeControlResponse, error)
	grpc.ClientStream
}

type pduServerWatchNodeControlClient struct {
	grpc.ClientStream
}

func (x *pduServerWatchNodeControlClient) Recv() (*NodeControlResponse, error) {
	m := new(NodeControlResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pduServerClient) WatchClientControl(ctx context.Context, in *ClientControlRequest, opts ...grpc.CallOption) (PduServer_WatchClientControlClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PduServer_serviceDesc.Streams[1], "/protos.PduServer/WatchClientControl", opts...)
	if err != nil {
		return nil, err
	}
	x := &pduServerWatchClientControlClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PduServer_WatchClientControlClient interface {
	Recv() (*ClientControlResponse, error)
	grpc.ClientStream
}

type pduServerWatchClientControlClient struct {
	grpc.ClientStream
}

func (x *pduServerWatchClientControlClient) Recv() (*ClientControlResponse, error) {
	m := new(ClientControlResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PduServerServer is the server API for PduServer service.
type PduServerServer interface {
	ClientHello(context.Context, *HelloRequest) (*HelloResponse, error)
	ClientCollect(context.Context, *CollectRequest) (*CollectResponse, error)
	NodeCollect(context.Context, *NodeCollectRequest) (*CollectResponse, error)
	WatchNodeControl(*NodeControlRequest, PduServer_WatchNodeControlServer) error
	WatchClientControl(*ClientControlRequest, PduServer_WatchClientControlServer) error
}

func RegisterPduServerServer(s *grpc.Server, srv PduServerServer) {
	s.RegisterService(&_PduServer_serviceDesc, srv)
}

func _PduServer_ClientHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PduServerServer).ClientHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.PduServer/ClientHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PduServerServer).ClientHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PduServer_ClientCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PduServerServer).ClientCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.PduServer/ClientCollect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PduServerServer).ClientCollect(ctx, req.(*CollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PduServer_NodeCollect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCollectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PduServerServer).NodeCollect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.PduServer/NodeCollect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PduServerServer).NodeCollect(ctx, req.(*NodeCollectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PduServer_WatchNodeControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeControlRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PduServerServer).WatchNodeControl(m, &pduServerWatchNodeControlServer{stream})
}

type PduServer_WatchNodeControlServer interface {
	Send(*NodeControlResponse) error
	grpc.ServerStream
}

type pduServerWatchNodeControlServer struct {
	grpc.ServerStream
}

func (x *pduServerWatchNodeControlServer) Send(m *NodeControlResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PduServer_WatchClientControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientControlRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PduServerServer).WatchClientControl(m, &pduServerWatchClientControlServer{stream})
}

type PduServer_WatchClientControlServer interface {
	Send(*ClientControlResponse) error
	grpc.ServerStream
}

type pduServerWatchClientControlServer struct {
	grpc.ServerStream
}

func (x *pduServerWatchClientControlServer) Send(m *ClientControlResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PduServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.PduServer",
	HandlerType: (*PduServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientHello",
			Handler:    _PduServer_ClientHello_Handler,
		},
		{
			MethodName: "ClientCollect",
			Handler:    _PduServer_ClientCollect_Handler,
		},
		{
			MethodName: "NodeCollect",
			Handler:    _PduServer_NodeCollect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNodeControl",
			Handler:       _PduServer_WatchNodeControl_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchClientControl",
			Handler:       _PduServer_WatchClientControl_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/pdu.proto",
}
